import = ["~/.config/alacritty/themes/catppuccin_latte.toml"]

# for new machines, update absolute path of ZDOTDIR
[env]
TERM = "screen-256color"
ZDOTDIR = "/Users/vvvetroff/.config/zsh"

[window]
padding.x = 0
padding.y = 0
dynamic_padding = true
decorations = "none"
opacity = 1
option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
normal.style = "Regular"
bold.family = "JetBrainsMono Nerd Font Mono"
bold.style = "Bold"
italic.family = "JetBrainsMono Nerd Font Mono"
italic.style = "Italic"
bold_italic.family = "JetBrainsMono Nerd Font Mono"
bold_italic.style = "Bold Italic"
size = 20

[keyboard]
bindings = [
  { key = "N", mods = "Command", action = "CreateNewWindow" }
]
